// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TaskExecutorStep.proto

package com.demo.v3;

public final class TaskExecutorStepBean {
  private TaskExecutorStepBean() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StepInfoOrBuilder extends
          // @@protoc_insertion_point(interface_extends:com.demo.v3.StepInfo)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 StepNo = 1;</code>
     */
    long getStepNo();

    /**
     * <code>string StepName = 2;</code>
     */
    java.lang.String getStepName();
    /**
     * <code>string StepName = 2;</code>
     */
    com.google.protobuf.ByteString
    getStepNameBytes();

    /**
     * <code>int32 StepStatus = 3;</code>
     */
    int getStepStatus();

    /**
     * <code>string Reason = 4;</code>
     */
    java.lang.String getReason();
    /**
     * <code>string Reason = 4;</code>
     */
    com.google.protobuf.ByteString
    getReasonBytes();

    /**
     * <code>string StartTime = 5;</code>
     */
    java.lang.String getStartTime();
    /**
     * <code>string StartTime = 5;</code>
     */
    com.google.protobuf.ByteString
    getStartTimeBytes();

    /**
     * <code>string EndTime = 6;</code>
     */
    java.lang.String getEndTime();
    /**
     * <code>string EndTime = 6;</code>
     */
    com.google.protobuf.ByteString
    getEndTimeBytes();
  }
  /**
   * Protobuf type {@code com.demo.v3.StepInfo}
   */
  public  static final class StepInfo extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:com.demo.v3.StepInfo)
          StepInfoOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use StepInfo.newBuilder() to construct.
    private StepInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StepInfo() {
      stepNo_ = 0L;
      stepName_ = "";
      stepStatus_ = 0;
      reason_ = "";
      startTime_ = "";
      endTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StepInfo(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              stepNo_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              stepName_ = s;
              break;
            }
            case 24: {

              stepStatus_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              reason_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              startTime_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              endTime_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.demo.v3.TaskExecutorStepBean.internal_static_com_demo_v3_StepInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.demo.v3.TaskExecutorStepBean.internal_static_com_demo_v3_StepInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.demo.v3.TaskExecutorStepBean.StepInfo.class, com.demo.v3.TaskExecutorStepBean.StepInfo.Builder.class);
    }

    public static final int STEPNO_FIELD_NUMBER = 1;
    private long stepNo_;
    /**
     * <code>int64 StepNo = 1;</code>
     */
    public long getStepNo() {
      return stepNo_;
    }

    public static final int STEPNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object stepName_;
    /**
     * <code>string StepName = 2;</code>
     */
    public java.lang.String getStepName() {
      java.lang.Object ref = stepName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stepName_ = s;
        return s;
      }
    }
    /**
     * <code>string StepName = 2;</code>
     */
    public com.google.protobuf.ByteString
    getStepNameBytes() {
      java.lang.Object ref = stepName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        stepName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STEPSTATUS_FIELD_NUMBER = 3;
    private int stepStatus_;
    /**
     * <code>int32 StepStatus = 3;</code>
     */
    public int getStepStatus() {
      return stepStatus_;
    }

    public static final int REASON_FIELD_NUMBER = 4;
    private volatile java.lang.Object reason_;
    /**
     * <code>string Reason = 4;</code>
     */
    public java.lang.String getReason() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reason_ = s;
        return s;
      }
    }
    /**
     * <code>string Reason = 4;</code>
     */
    public com.google.protobuf.ByteString
    getReasonBytes() {
      java.lang.Object ref = reason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        reason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 5;
    private volatile java.lang.Object startTime_;
    /**
     * <code>string StartTime = 5;</code>
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      }
    }
    /**
     * <code>string StartTime = 5;</code>
     */
    public com.google.protobuf.ByteString
    getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDTIME_FIELD_NUMBER = 6;
    private volatile java.lang.Object endTime_;
    /**
     * <code>string EndTime = 6;</code>
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      }
    }
    /**
     * <code>string EndTime = 6;</code>
     */
    public com.google.protobuf.ByteString
    getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (stepNo_ != 0L) {
        output.writeInt64(1, stepNo_);
      }
      if (!getStepNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stepName_);
      }
      if (stepStatus_ != 0) {
        output.writeInt32(3, stepStatus_);
      }
      if (!getReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, reason_);
      }
      if (!getStartTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, startTime_);
      }
      if (!getEndTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, endTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stepNo_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt64Size(1, stepNo_);
      }
      if (!getStepNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stepName_);
      }
      if (stepStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(3, stepStatus_);
      }
      if (!getReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, reason_);
      }
      if (!getStartTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, startTime_);
      }
      if (!getEndTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, endTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.demo.v3.TaskExecutorStepBean.StepInfo)) {
        return super.equals(obj);
      }
      com.demo.v3.TaskExecutorStepBean.StepInfo other = (com.demo.v3.TaskExecutorStepBean.StepInfo) obj;

      boolean result = true;
      result = result && (getStepNo()
              == other.getStepNo());
      result = result && getStepName()
              .equals(other.getStepName());
      result = result && (getStepStatus()
              == other.getStepStatus());
      result = result && getReason()
              .equals(other.getReason());
      result = result && getStartTime()
              .equals(other.getStartTime());
      result = result && getEndTime()
              .equals(other.getEndTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STEPNO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getStepNo());
      hash = (37 * hash) + STEPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getStepName().hashCode();
      hash = (37 * hash) + STEPSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStepStatus();
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartTime().hashCode();
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getEndTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.demo.v3.TaskExecutorStepBean.StepInfo parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.v3.TaskExecutorStepBean.StepInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.demo.v3.StepInfo}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.demo.v3.StepInfo)
            com.demo.v3.TaskExecutorStepBean.StepInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.demo.v3.TaskExecutorStepBean.internal_static_com_demo_v3_StepInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.demo.v3.TaskExecutorStepBean.internal_static_com_demo_v3_StepInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.demo.v3.TaskExecutorStepBean.StepInfo.class, com.demo.v3.TaskExecutorStepBean.StepInfo.Builder.class);
      }

      // Construct using com.demo.v3.TaskExecutorStepBean.StepInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        stepNo_ = 0L;

        stepName_ = "";

        stepStatus_ = 0;

        reason_ = "";

        startTime_ = "";

        endTime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.demo.v3.TaskExecutorStepBean.internal_static_com_demo_v3_StepInfo_descriptor;
      }

      public com.demo.v3.TaskExecutorStepBean.StepInfo getDefaultInstanceForType() {
        return com.demo.v3.TaskExecutorStepBean.StepInfo.getDefaultInstance();
      }

      public com.demo.v3.TaskExecutorStepBean.StepInfo build() {
        com.demo.v3.TaskExecutorStepBean.StepInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.v3.TaskExecutorStepBean.StepInfo buildPartial() {
        com.demo.v3.TaskExecutorStepBean.StepInfo result = new com.demo.v3.TaskExecutorStepBean.StepInfo(this);
        result.stepNo_ = stepNo_;
        result.stepName_ = stepName_;
        result.stepStatus_ = stepStatus_;
        result.reason_ = reason_;
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.v3.TaskExecutorStepBean.StepInfo) {
          return mergeFrom((com.demo.v3.TaskExecutorStepBean.StepInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.v3.TaskExecutorStepBean.StepInfo other) {
        if (other == com.demo.v3.TaskExecutorStepBean.StepInfo.getDefaultInstance()) return this;
        if (other.getStepNo() != 0L) {
          setStepNo(other.getStepNo());
        }
        if (!other.getStepName().isEmpty()) {
          stepName_ = other.stepName_;
          onChanged();
        }
        if (other.getStepStatus() != 0) {
          setStepStatus(other.getStepStatus());
        }
        if (!other.getReason().isEmpty()) {
          reason_ = other.reason_;
          onChanged();
        }
        if (!other.getStartTime().isEmpty()) {
          startTime_ = other.startTime_;
          onChanged();
        }
        if (!other.getEndTime().isEmpty()) {
          endTime_ = other.endTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.demo.v3.TaskExecutorStepBean.StepInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.v3.TaskExecutorStepBean.StepInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long stepNo_ ;
      /**
       * <code>int64 StepNo = 1;</code>
       */
      public long getStepNo() {
        return stepNo_;
      }
      /**
       * <code>int64 StepNo = 1;</code>
       */
      public Builder setStepNo(long value) {

        stepNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 StepNo = 1;</code>
       */
      public Builder clearStepNo() {

        stepNo_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object stepName_ = "";
      /**
       * <code>string StepName = 2;</code>
       */
      public java.lang.String getStepName() {
        java.lang.Object ref = stepName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stepName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string StepName = 2;</code>
       */
      public com.google.protobuf.ByteString
      getStepNameBytes() {
        java.lang.Object ref = stepName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          stepName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string StepName = 2;</code>
       */
      public Builder setStepName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        stepName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string StepName = 2;</code>
       */
      public Builder clearStepName() {

        stepName_ = getDefaultInstance().getStepName();
        onChanged();
        return this;
      }
      /**
       * <code>string StepName = 2;</code>
       */
      public Builder setStepNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        stepName_ = value;
        onChanged();
        return this;
      }

      private int stepStatus_ ;
      /**
       * <code>int32 StepStatus = 3;</code>
       */
      public int getStepStatus() {
        return stepStatus_;
      }
      /**
       * <code>int32 StepStatus = 3;</code>
       */
      public Builder setStepStatus(int value) {

        stepStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 StepStatus = 3;</code>
       */
      public Builder clearStepStatus() {

        stepStatus_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object reason_ = "";
      /**
       * <code>string Reason = 4;</code>
       */
      public java.lang.String getReason() {
        java.lang.Object ref = reason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Reason = 4;</code>
       */
      public com.google.protobuf.ByteString
      getReasonBytes() {
        java.lang.Object ref = reason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          reason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Reason = 4;</code>
       */
      public Builder setReason(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Reason = 4;</code>
       */
      public Builder clearReason() {

        reason_ = getDefaultInstance().getReason();
        onChanged();
        return this;
      }
      /**
       * <code>string Reason = 4;</code>
       */
      public Builder setReasonBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        reason_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object startTime_ = "";
      /**
       * <code>string StartTime = 5;</code>
       */
      public java.lang.String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string StartTime = 5;</code>
       */
      public com.google.protobuf.ByteString
      getStartTimeBytes() {
        java.lang.Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string StartTime = 5;</code>
       */
      public Builder setStartTime(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string StartTime = 5;</code>
       */
      public Builder clearStartTime() {

        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>string StartTime = 5;</code>
       */
      public Builder setStartTimeBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        startTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endTime_ = "";
      /**
       * <code>string EndTime = 6;</code>
       */
      public java.lang.String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string EndTime = 6;</code>
       */
      public com.google.protobuf.ByteString
      getEndTimeBytes() {
        java.lang.Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string EndTime = 6;</code>
       */
      public Builder setEndTime(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string EndTime = 6;</code>
       */
      public Builder clearEndTime() {

        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <code>string EndTime = 6;</code>
       */
      public Builder setEndTimeBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        endTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.demo.v3.StepInfo)
    }

    // @@protoc_insertion_point(class_scope:com.demo.v3.StepInfo)
    private static final com.demo.v3.TaskExecutorStepBean.StepInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.v3.TaskExecutorStepBean.StepInfo();
    }

    public static com.demo.v3.TaskExecutorStepBean.StepInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StepInfo>
            PARSER = new com.google.protobuf.AbstractParser<StepInfo>() {
      public StepInfo parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new StepInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StepInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StepInfo> getParserForType() {
      return PARSER;
    }

    public com.demo.v3.TaskExecutorStepBean.StepInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskExecutorStepOrBuilder extends
          // @@protoc_insertion_point(interface_extends:com.demo.v3.TaskExecutorStep)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string StationID = 1;</code>
     */
    java.lang.String getStationID();
    /**
     * <code>string StationID = 1;</code>
     */
    com.google.protobuf.ByteString
    getStationIDBytes();

    /**
     * <code>string TimeTag = 2;</code>
     */
    java.lang.String getTimeTag();
    /**
     * <code>string TimeTag = 2;</code>
     */
    com.google.protobuf.ByteString
    getTimeTagBytes();

    /**
     * <code>string AntennaID = 3;</code>
     */
    java.lang.String getAntennaID();
    /**
     * <code>string AntennaID = 3;</code>
     */
    com.google.protobuf.ByteString
    getAntennaIDBytes();

    /**
     * <code>string AntennaName = 4;</code>
     */
    java.lang.String getAntennaName();
    /**
     * <code>string AntennaName = 4;</code>
     */
    com.google.protobuf.ByteString
    getAntennaNameBytes();

    /**
     * <code>string scheduleID = 5;</code>
     */
    java.lang.String getScheduleID();
    /**
     * <code>string scheduleID = 5;</code>
     */
    com.google.protobuf.ByteString
    getScheduleIDBytes();

    /**
     * <code>string jobTaskID = 6;</code>
     */
    java.lang.String getJobTaskID();
    /**
     * <code>string jobTaskID = 6;</code>
     */
    com.google.protobuf.ByteString
    getJobTaskIDBytes();

    /**
     * <code>string SatelliteName = 7;</code>
     */
    java.lang.String getSatelliteName();
    /**
     * <code>string SatelliteName = 7;</code>
     */
    com.google.protobuf.ByteString
    getSatelliteNameBytes();

    /**
     * <code>int32 SatDataBand = 8;</code>
     */
    int getSatDataBand();

    /**
     * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
     */
    java.util.List<com.demo.v3.TaskExecutorStepBean.StepInfo>
    getStepsList();
    /**
     * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
     */
    com.demo.v3.TaskExecutorStepBean.StepInfo getSteps(int index);
    /**
     * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
     */
    int getStepsCount();
    /**
     * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
     */
    java.util.List<? extends com.demo.v3.TaskExecutorStepBean.StepInfoOrBuilder>
    getStepsOrBuilderList();
    /**
     * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
     */
    com.demo.v3.TaskExecutorStepBean.StepInfoOrBuilder getStepsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code com.demo.v3.TaskExecutorStep}
   */
  public  static final class TaskExecutorStep extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:com.demo.v3.TaskExecutorStep)
          TaskExecutorStepOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use TaskExecutorStep.newBuilder() to construct.
    private TaskExecutorStep(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskExecutorStep() {
      stationID_ = "";
      timeTag_ = "";
      antennaID_ = "";
      antennaName_ = "";
      scheduleID_ = "";
      jobTaskID_ = "";
      satelliteName_ = "";
      satDataBand_ = 0;
      steps_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskExecutorStep(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              stationID_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              timeTag_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              antennaID_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              antennaName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              scheduleID_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              jobTaskID_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              satelliteName_ = s;
              break;
            }
            case 64: {

              satDataBand_ = input.readInt32();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                steps_ = new java.util.ArrayList<com.demo.v3.TaskExecutorStepBean.StepInfo>();
                mutable_bitField0_ |= 0x00000100;
              }
              steps_.add(
                      input.readMessage(com.demo.v3.TaskExecutorStepBean.StepInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          steps_ = java.util.Collections.unmodifiableList(steps_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.demo.v3.TaskExecutorStepBean.internal_static_com_demo_v3_TaskExecutorStep_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.demo.v3.TaskExecutorStepBean.internal_static_com_demo_v3_TaskExecutorStep_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.demo.v3.TaskExecutorStepBean.TaskExecutorStep.class, com.demo.v3.TaskExecutorStepBean.TaskExecutorStep.Builder.class);
    }

    private int bitField0_;
    public static final int STATIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object stationID_;
    /**
     * <code>string StationID = 1;</code>
     */
    public java.lang.String getStationID() {
      java.lang.Object ref = stationID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stationID_ = s;
        return s;
      }
    }
    /**
     * <code>string StationID = 1;</code>
     */
    public com.google.protobuf.ByteString
    getStationIDBytes() {
      java.lang.Object ref = stationID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        stationID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMETAG_FIELD_NUMBER = 2;
    private volatile java.lang.Object timeTag_;
    /**
     * <code>string TimeTag = 2;</code>
     */
    public java.lang.String getTimeTag() {
      java.lang.Object ref = timeTag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeTag_ = s;
        return s;
      }
    }
    /**
     * <code>string TimeTag = 2;</code>
     */
    public com.google.protobuf.ByteString
    getTimeTagBytes() {
      java.lang.Object ref = timeTag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        timeTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANTENNAID_FIELD_NUMBER = 3;
    private volatile java.lang.Object antennaID_;
    /**
     * <code>string AntennaID = 3;</code>
     */
    public java.lang.String getAntennaID() {
      java.lang.Object ref = antennaID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        antennaID_ = s;
        return s;
      }
    }
    /**
     * <code>string AntennaID = 3;</code>
     */
    public com.google.protobuf.ByteString
    getAntennaIDBytes() {
      java.lang.Object ref = antennaID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        antennaID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANTENNANAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object antennaName_;
    /**
     * <code>string AntennaName = 4;</code>
     */
    public java.lang.String getAntennaName() {
      java.lang.Object ref = antennaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        antennaName_ = s;
        return s;
      }
    }
    /**
     * <code>string AntennaName = 4;</code>
     */
    public com.google.protobuf.ByteString
    getAntennaNameBytes() {
      java.lang.Object ref = antennaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        antennaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCHEDULEID_FIELD_NUMBER = 5;
    private volatile java.lang.Object scheduleID_;
    /**
     * <code>string scheduleID = 5;</code>
     */
    public java.lang.String getScheduleID() {
      java.lang.Object ref = scheduleID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheduleID_ = s;
        return s;
      }
    }
    /**
     * <code>string scheduleID = 5;</code>
     */
    public com.google.protobuf.ByteString
    getScheduleIDBytes() {
      java.lang.Object ref = scheduleID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        scheduleID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOBTASKID_FIELD_NUMBER = 6;
    private volatile java.lang.Object jobTaskID_;
    /**
     * <code>string jobTaskID = 6;</code>
     */
    public java.lang.String getJobTaskID() {
      java.lang.Object ref = jobTaskID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jobTaskID_ = s;
        return s;
      }
    }
    /**
     * <code>string jobTaskID = 6;</code>
     */
    public com.google.protobuf.ByteString
    getJobTaskIDBytes() {
      java.lang.Object ref = jobTaskID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        jobTaskID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SATELLITENAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object satelliteName_;
    /**
     * <code>string SatelliteName = 7;</code>
     */
    public java.lang.String getSatelliteName() {
      java.lang.Object ref = satelliteName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        satelliteName_ = s;
        return s;
      }
    }
    /**
     * <code>string SatelliteName = 7;</code>
     */
    public com.google.protobuf.ByteString
    getSatelliteNameBytes() {
      java.lang.Object ref = satelliteName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        satelliteName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SATDATABAND_FIELD_NUMBER = 8;
    private int satDataBand_;
    /**
     * <code>int32 SatDataBand = 8;</code>
     */
    public int getSatDataBand() {
      return satDataBand_;
    }

    public static final int STEPS_FIELD_NUMBER = 9;
    private java.util.List<com.demo.v3.TaskExecutorStepBean.StepInfo> steps_;
    /**
     * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
     */
    public java.util.List<com.demo.v3.TaskExecutorStepBean.StepInfo> getStepsList() {
      return steps_;
    }
    /**
     * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
     */
    public java.util.List<? extends com.demo.v3.TaskExecutorStepBean.StepInfoOrBuilder>
    getStepsOrBuilderList() {
      return steps_;
    }
    /**
     * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
     */
    public int getStepsCount() {
      return steps_.size();
    }
    /**
     * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
     */
    public com.demo.v3.TaskExecutorStepBean.StepInfo getSteps(int index) {
      return steps_.get(index);
    }
    /**
     * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
     */
    public com.demo.v3.TaskExecutorStepBean.StepInfoOrBuilder getStepsOrBuilder(
            int index) {
      return steps_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getStationIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stationID_);
      }
      if (!getTimeTagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeTag_);
      }
      if (!getAntennaIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, antennaID_);
      }
      if (!getAntennaNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, antennaName_);
      }
      if (!getScheduleIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, scheduleID_);
      }
      if (!getJobTaskIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, jobTaskID_);
      }
      if (!getSatelliteNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, satelliteName_);
      }
      if (satDataBand_ != 0) {
        output.writeInt32(8, satDataBand_);
      }
      for (int i = 0; i < steps_.size(); i++) {
        output.writeMessage(9, steps_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStationIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stationID_);
      }
      if (!getTimeTagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeTag_);
      }
      if (!getAntennaIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, antennaID_);
      }
      if (!getAntennaNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, antennaName_);
      }
      if (!getScheduleIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, scheduleID_);
      }
      if (!getJobTaskIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, jobTaskID_);
      }
      if (!getSatelliteNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, satelliteName_);
      }
      if (satDataBand_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(8, satDataBand_);
      }
      for (int i = 0; i < steps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(9, steps_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.demo.v3.TaskExecutorStepBean.TaskExecutorStep)) {
        return super.equals(obj);
      }
      com.demo.v3.TaskExecutorStepBean.TaskExecutorStep other = (com.demo.v3.TaskExecutorStepBean.TaskExecutorStep) obj;

      boolean result = true;
      result = result && getStationID()
              .equals(other.getStationID());
      result = result && getTimeTag()
              .equals(other.getTimeTag());
      result = result && getAntennaID()
              .equals(other.getAntennaID());
      result = result && getAntennaName()
              .equals(other.getAntennaName());
      result = result && getScheduleID()
              .equals(other.getScheduleID());
      result = result && getJobTaskID()
              .equals(other.getJobTaskID());
      result = result && getSatelliteName()
              .equals(other.getSatelliteName());
      result = result && (getSatDataBand()
              == other.getSatDataBand());
      result = result && getStepsList()
              .equals(other.getStepsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getStationID().hashCode();
      hash = (37 * hash) + TIMETAG_FIELD_NUMBER;
      hash = (53 * hash) + getTimeTag().hashCode();
      hash = (37 * hash) + ANTENNAID_FIELD_NUMBER;
      hash = (53 * hash) + getAntennaID().hashCode();
      hash = (37 * hash) + ANTENNANAME_FIELD_NUMBER;
      hash = (53 * hash) + getAntennaName().hashCode();
      hash = (37 * hash) + SCHEDULEID_FIELD_NUMBER;
      hash = (53 * hash) + getScheduleID().hashCode();
      hash = (37 * hash) + JOBTASKID_FIELD_NUMBER;
      hash = (53 * hash) + getJobTaskID().hashCode();
      hash = (37 * hash) + SATELLITENAME_FIELD_NUMBER;
      hash = (53 * hash) + getSatelliteName().hashCode();
      hash = (37 * hash) + SATDATABAND_FIELD_NUMBER;
      hash = (53 * hash) + getSatDataBand();
      if (getStepsCount() > 0) {
        hash = (37 * hash) + STEPS_FIELD_NUMBER;
        hash = (53 * hash) + getStepsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.demo.v3.TaskExecutorStepBean.TaskExecutorStep prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.demo.v3.TaskExecutorStep}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.demo.v3.TaskExecutorStep)
            com.demo.v3.TaskExecutorStepBean.TaskExecutorStepOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.demo.v3.TaskExecutorStepBean.internal_static_com_demo_v3_TaskExecutorStep_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.demo.v3.TaskExecutorStepBean.internal_static_com_demo_v3_TaskExecutorStep_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.demo.v3.TaskExecutorStepBean.TaskExecutorStep.class, com.demo.v3.TaskExecutorStepBean.TaskExecutorStep.Builder.class);
      }

      // Construct using com.demo.v3.TaskExecutorStepBean.TaskExecutorStep.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStepsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        stationID_ = "";

        timeTag_ = "";

        antennaID_ = "";

        antennaName_ = "";

        scheduleID_ = "";

        jobTaskID_ = "";

        satelliteName_ = "";

        satDataBand_ = 0;

        if (stepsBuilder_ == null) {
          steps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          stepsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.demo.v3.TaskExecutorStepBean.internal_static_com_demo_v3_TaskExecutorStep_descriptor;
      }

      public com.demo.v3.TaskExecutorStepBean.TaskExecutorStep getDefaultInstanceForType() {
        return com.demo.v3.TaskExecutorStepBean.TaskExecutorStep.getDefaultInstance();
      }

      public com.demo.v3.TaskExecutorStepBean.TaskExecutorStep build() {
        com.demo.v3.TaskExecutorStepBean.TaskExecutorStep result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.demo.v3.TaskExecutorStepBean.TaskExecutorStep buildPartial() {
        com.demo.v3.TaskExecutorStepBean.TaskExecutorStep result = new com.demo.v3.TaskExecutorStepBean.TaskExecutorStep(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.stationID_ = stationID_;
        result.timeTag_ = timeTag_;
        result.antennaID_ = antennaID_;
        result.antennaName_ = antennaName_;
        result.scheduleID_ = scheduleID_;
        result.jobTaskID_ = jobTaskID_;
        result.satelliteName_ = satelliteName_;
        result.satDataBand_ = satDataBand_;
        if (stepsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            steps_ = java.util.Collections.unmodifiableList(steps_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.steps_ = steps_;
        } else {
          result.steps_ = stepsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.demo.v3.TaskExecutorStepBean.TaskExecutorStep) {
          return mergeFrom((com.demo.v3.TaskExecutorStepBean.TaskExecutorStep)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.demo.v3.TaskExecutorStepBean.TaskExecutorStep other) {
        if (other == com.demo.v3.TaskExecutorStepBean.TaskExecutorStep.getDefaultInstance()) return this;
        if (!other.getStationID().isEmpty()) {
          stationID_ = other.stationID_;
          onChanged();
        }
        if (!other.getTimeTag().isEmpty()) {
          timeTag_ = other.timeTag_;
          onChanged();
        }
        if (!other.getAntennaID().isEmpty()) {
          antennaID_ = other.antennaID_;
          onChanged();
        }
        if (!other.getAntennaName().isEmpty()) {
          antennaName_ = other.antennaName_;
          onChanged();
        }
        if (!other.getScheduleID().isEmpty()) {
          scheduleID_ = other.scheduleID_;
          onChanged();
        }
        if (!other.getJobTaskID().isEmpty()) {
          jobTaskID_ = other.jobTaskID_;
          onChanged();
        }
        if (!other.getSatelliteName().isEmpty()) {
          satelliteName_ = other.satelliteName_;
          onChanged();
        }
        if (other.getSatDataBand() != 0) {
          setSatDataBand(other.getSatDataBand());
        }
        if (stepsBuilder_ == null) {
          if (!other.steps_.isEmpty()) {
            if (steps_.isEmpty()) {
              steps_ = other.steps_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureStepsIsMutable();
              steps_.addAll(other.steps_);
            }
            onChanged();
          }
        } else {
          if (!other.steps_.isEmpty()) {
            if (stepsBuilder_.isEmpty()) {
              stepsBuilder_.dispose();
              stepsBuilder_ = null;
              steps_ = other.steps_;
              bitField0_ = (bitField0_ & ~0x00000100);
              stepsBuilder_ =
                      com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                              getStepsFieldBuilder() : null;
            } else {
              stepsBuilder_.addAllMessages(other.steps_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.demo.v3.TaskExecutorStepBean.TaskExecutorStep parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.demo.v3.TaskExecutorStepBean.TaskExecutorStep) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stationID_ = "";
      /**
       * <code>string StationID = 1;</code>
       */
      public java.lang.String getStationID() {
        java.lang.Object ref = stationID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stationID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string StationID = 1;</code>
       */
      public com.google.protobuf.ByteString
      getStationIDBytes() {
        java.lang.Object ref = stationID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          stationID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string StationID = 1;</code>
       */
      public Builder setStationID(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        stationID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string StationID = 1;</code>
       */
      public Builder clearStationID() {

        stationID_ = getDefaultInstance().getStationID();
        onChanged();
        return this;
      }
      /**
       * <code>string StationID = 1;</code>
       */
      public Builder setStationIDBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        stationID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timeTag_ = "";
      /**
       * <code>string TimeTag = 2;</code>
       */
      public java.lang.String getTimeTag() {
        java.lang.Object ref = timeTag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeTag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string TimeTag = 2;</code>
       */
      public com.google.protobuf.ByteString
      getTimeTagBytes() {
        java.lang.Object ref = timeTag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          timeTag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string TimeTag = 2;</code>
       */
      public Builder setTimeTag(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        timeTag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string TimeTag = 2;</code>
       */
      public Builder clearTimeTag() {

        timeTag_ = getDefaultInstance().getTimeTag();
        onChanged();
        return this;
      }
      /**
       * <code>string TimeTag = 2;</code>
       */
      public Builder setTimeTagBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        timeTag_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object antennaID_ = "";
      /**
       * <code>string AntennaID = 3;</code>
       */
      public java.lang.String getAntennaID() {
        java.lang.Object ref = antennaID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          antennaID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string AntennaID = 3;</code>
       */
      public com.google.protobuf.ByteString
      getAntennaIDBytes() {
        java.lang.Object ref = antennaID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          antennaID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string AntennaID = 3;</code>
       */
      public Builder setAntennaID(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        antennaID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string AntennaID = 3;</code>
       */
      public Builder clearAntennaID() {

        antennaID_ = getDefaultInstance().getAntennaID();
        onChanged();
        return this;
      }
      /**
       * <code>string AntennaID = 3;</code>
       */
      public Builder setAntennaIDBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        antennaID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object antennaName_ = "";
      /**
       * <code>string AntennaName = 4;</code>
       */
      public java.lang.String getAntennaName() {
        java.lang.Object ref = antennaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          antennaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string AntennaName = 4;</code>
       */
      public com.google.protobuf.ByteString
      getAntennaNameBytes() {
        java.lang.Object ref = antennaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          antennaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string AntennaName = 4;</code>
       */
      public Builder setAntennaName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        antennaName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string AntennaName = 4;</code>
       */
      public Builder clearAntennaName() {

        antennaName_ = getDefaultInstance().getAntennaName();
        onChanged();
        return this;
      }
      /**
       * <code>string AntennaName = 4;</code>
       */
      public Builder setAntennaNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        antennaName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object scheduleID_ = "";
      /**
       * <code>string scheduleID = 5;</code>
       */
      public java.lang.String getScheduleID() {
        java.lang.Object ref = scheduleID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          scheduleID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string scheduleID = 5;</code>
       */
      public com.google.protobuf.ByteString
      getScheduleIDBytes() {
        java.lang.Object ref = scheduleID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          scheduleID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string scheduleID = 5;</code>
       */
      public Builder setScheduleID(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        scheduleID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string scheduleID = 5;</code>
       */
      public Builder clearScheduleID() {

        scheduleID_ = getDefaultInstance().getScheduleID();
        onChanged();
        return this;
      }
      /**
       * <code>string scheduleID = 5;</code>
       */
      public Builder setScheduleIDBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        scheduleID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object jobTaskID_ = "";
      /**
       * <code>string jobTaskID = 6;</code>
       */
      public java.lang.String getJobTaskID() {
        java.lang.Object ref = jobTaskID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jobTaskID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string jobTaskID = 6;</code>
       */
      public com.google.protobuf.ByteString
      getJobTaskIDBytes() {
        java.lang.Object ref = jobTaskID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          jobTaskID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string jobTaskID = 6;</code>
       */
      public Builder setJobTaskID(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        jobTaskID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string jobTaskID = 6;</code>
       */
      public Builder clearJobTaskID() {

        jobTaskID_ = getDefaultInstance().getJobTaskID();
        onChanged();
        return this;
      }
      /**
       * <code>string jobTaskID = 6;</code>
       */
      public Builder setJobTaskIDBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        jobTaskID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object satelliteName_ = "";
      /**
       * <code>string SatelliteName = 7;</code>
       */
      public java.lang.String getSatelliteName() {
        java.lang.Object ref = satelliteName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          satelliteName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string SatelliteName = 7;</code>
       */
      public com.google.protobuf.ByteString
      getSatelliteNameBytes() {
        java.lang.Object ref = satelliteName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          satelliteName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string SatelliteName = 7;</code>
       */
      public Builder setSatelliteName(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        satelliteName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string SatelliteName = 7;</code>
       */
      public Builder clearSatelliteName() {

        satelliteName_ = getDefaultInstance().getSatelliteName();
        onChanged();
        return this;
      }
      /**
       * <code>string SatelliteName = 7;</code>
       */
      public Builder setSatelliteNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        satelliteName_ = value;
        onChanged();
        return this;
      }

      private int satDataBand_ ;
      /**
       * <code>int32 SatDataBand = 8;</code>
       */
      public int getSatDataBand() {
        return satDataBand_;
      }
      /**
       * <code>int32 SatDataBand = 8;</code>
       */
      public Builder setSatDataBand(int value) {

        satDataBand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 SatDataBand = 8;</code>
       */
      public Builder clearSatDataBand() {

        satDataBand_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.demo.v3.TaskExecutorStepBean.StepInfo> steps_ =
              java.util.Collections.emptyList();
      private void ensureStepsIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          steps_ = new java.util.ArrayList<com.demo.v3.TaskExecutorStepBean.StepInfo>(steps_);
          bitField0_ |= 0x00000100;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              com.demo.v3.TaskExecutorStepBean.StepInfo, com.demo.v3.TaskExecutorStepBean.StepInfo.Builder, com.demo.v3.TaskExecutorStepBean.StepInfoOrBuilder> stepsBuilder_;

      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public java.util.List<com.demo.v3.TaskExecutorStepBean.StepInfo> getStepsList() {
        if (stepsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(steps_);
        } else {
          return stepsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public int getStepsCount() {
        if (stepsBuilder_ == null) {
          return steps_.size();
        } else {
          return stepsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public com.demo.v3.TaskExecutorStepBean.StepInfo getSteps(int index) {
        if (stepsBuilder_ == null) {
          return steps_.get(index);
        } else {
          return stepsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public Builder setSteps(
              int index, com.demo.v3.TaskExecutorStepBean.StepInfo value) {
        if (stepsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStepsIsMutable();
          steps_.set(index, value);
          onChanged();
        } else {
          stepsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public Builder setSteps(
              int index, com.demo.v3.TaskExecutorStepBean.StepInfo.Builder builderForValue) {
        if (stepsBuilder_ == null) {
          ensureStepsIsMutable();
          steps_.set(index, builderForValue.build());
          onChanged();
        } else {
          stepsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public Builder addSteps(com.demo.v3.TaskExecutorStepBean.StepInfo value) {
        if (stepsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStepsIsMutable();
          steps_.add(value);
          onChanged();
        } else {
          stepsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public Builder addSteps(
              int index, com.demo.v3.TaskExecutorStepBean.StepInfo value) {
        if (stepsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStepsIsMutable();
          steps_.add(index, value);
          onChanged();
        } else {
          stepsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public Builder addSteps(
              com.demo.v3.TaskExecutorStepBean.StepInfo.Builder builderForValue) {
        if (stepsBuilder_ == null) {
          ensureStepsIsMutable();
          steps_.add(builderForValue.build());
          onChanged();
        } else {
          stepsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public Builder addSteps(
              int index, com.demo.v3.TaskExecutorStepBean.StepInfo.Builder builderForValue) {
        if (stepsBuilder_ == null) {
          ensureStepsIsMutable();
          steps_.add(index, builderForValue.build());
          onChanged();
        } else {
          stepsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public Builder addAllSteps(
              java.lang.Iterable<? extends com.demo.v3.TaskExecutorStepBean.StepInfo> values) {
        if (stepsBuilder_ == null) {
          ensureStepsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, steps_);
          onChanged();
        } else {
          stepsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public Builder clearSteps() {
        if (stepsBuilder_ == null) {
          steps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          stepsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public Builder removeSteps(int index) {
        if (stepsBuilder_ == null) {
          ensureStepsIsMutable();
          steps_.remove(index);
          onChanged();
        } else {
          stepsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public com.demo.v3.TaskExecutorStepBean.StepInfo.Builder getStepsBuilder(
              int index) {
        return getStepsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public com.demo.v3.TaskExecutorStepBean.StepInfoOrBuilder getStepsOrBuilder(
              int index) {
        if (stepsBuilder_ == null) {
          return steps_.get(index);  } else {
          return stepsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public java.util.List<? extends com.demo.v3.TaskExecutorStepBean.StepInfoOrBuilder>
      getStepsOrBuilderList() {
        if (stepsBuilder_ != null) {
          return stepsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(steps_);
        }
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public com.demo.v3.TaskExecutorStepBean.StepInfo.Builder addStepsBuilder() {
        return getStepsFieldBuilder().addBuilder(
                com.demo.v3.TaskExecutorStepBean.StepInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public com.demo.v3.TaskExecutorStepBean.StepInfo.Builder addStepsBuilder(
              int index) {
        return getStepsFieldBuilder().addBuilder(
                index, com.demo.v3.TaskExecutorStepBean.StepInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .com.demo.v3.StepInfo Steps = 9;</code>
       */
      public java.util.List<com.demo.v3.TaskExecutorStepBean.StepInfo.Builder>
      getStepsBuilderList() {
        return getStepsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
              com.demo.v3.TaskExecutorStepBean.StepInfo, com.demo.v3.TaskExecutorStepBean.StepInfo.Builder, com.demo.v3.TaskExecutorStepBean.StepInfoOrBuilder>
      getStepsFieldBuilder() {
        if (stepsBuilder_ == null) {
          stepsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                  com.demo.v3.TaskExecutorStepBean.StepInfo, com.demo.v3.TaskExecutorStepBean.StepInfo.Builder, com.demo.v3.TaskExecutorStepBean.StepInfoOrBuilder>(
                  steps_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          steps_ = null;
        }
        return stepsBuilder_;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.demo.v3.TaskExecutorStep)
    }

    // @@protoc_insertion_point(class_scope:com.demo.v3.TaskExecutorStep)
    private static final com.demo.v3.TaskExecutorStepBean.TaskExecutorStep DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.demo.v3.TaskExecutorStepBean.TaskExecutorStep();
    }

    public static com.demo.v3.TaskExecutorStepBean.TaskExecutorStep getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskExecutorStep>
            PARSER = new com.google.protobuf.AbstractParser<TaskExecutorStep>() {
      public TaskExecutorStep parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskExecutorStep(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskExecutorStep> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskExecutorStep> getParserForType() {
      return PARSER;
    }

    public com.demo.v3.TaskExecutorStepBean.TaskExecutorStep getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_demo_v3_StepInfo_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_demo_v3_StepInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_com_demo_v3_TaskExecutorStep_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_com_demo_v3_TaskExecutorStep_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\026TaskExecutorStep.proto\022\013com.demo.v3\"t\n" +
                    "\010StepInfo\022\016\n\006StepNo\030\001 \001(\003\022\020\n\010StepName\030\002 " +
                    "\001(\t\022\022\n\nStepStatus\030\003 \001(\005\022\016\n\006Reason\030\004 \001(\t\022" +
                    "\021\n\tStartTime\030\005 \001(\t\022\017\n\007EndTime\030\006 \001(\t\"\327\001\n\020" +
                    "TaskExecutorStep\022\021\n\tStationID\030\001 \001(\t\022\017\n\007T" +
                    "imeTag\030\002 \001(\t\022\021\n\tAntennaID\030\003 \001(\t\022\023\n\013Anten" +
                    "naName\030\004 \001(\t\022\022\n\nscheduleID\030\005 \001(\t\022\021\n\tjobT" +
                    "askID\030\006 \001(\t\022\025\n\rSatelliteName\030\007 \001(\t\022\023\n\013Sa" +
                    "tDataBand\030\010 \001(\005\022$\n\005Steps\030\t \003(\0132\025.com.dem" +
                    "o.v3.StepInfoB#\n\013com.demo.v3B\024TaskExecut" +
                    "orStepBeanb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_com_demo_v3_StepInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_v3_StepInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_demo_v3_StepInfo_descriptor,
            new java.lang.String[] { "StepNo", "StepName", "StepStatus", "Reason", "StartTime", "EndTime", });
    internal_static_com_demo_v3_TaskExecutorStep_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_com_demo_v3_TaskExecutorStep_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_demo_v3_TaskExecutorStep_descriptor,
            new java.lang.String[] { "StationID", "TimeTag", "AntennaID", "AntennaName", "ScheduleID", "JobTaskID", "SatelliteName", "SatDataBand", "Steps", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
